apiVersion: v1
kind: Service
metadata:
    name: thomsonsbuildpipelinedemo
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetPort: 8080
    selector:
        app: thomsonsbuildpipelinedemo